import { useRef, useState } from "react";
import { m, AnimatePresence } from "framer-motion";
import { Play, RotateCcw, Check, CheckCheck, Phone, MoreVertical, Sheet, Upload, FileSpreadsheet } from "lucide-react";
import { streamDemo } from "../../lib/demoClient";
import { track } from "../../lib/analytics";

// One contact "in the CRM". `interest` is editable so a visitor can change it
// and watch the AI re-personalize for real. `reply` is a scripted inbound
// response — only the outbound message is live-generated by the model.
type Lead = {
  id: number;
  name: string;
  company: string;
  interest: string;
  city: string;
  source: string;
  phone?: string;
  color: string;
  reply?: string;
};

type Status = "idle" | "writing" | "sent" | "delivered" | "read" | "replied" | "responding" | "booked";

const STEP = ["idle", "writing", "sent", "delivered", "read", "replied", "responding", "booked"] as const;
const reached = (s: Status, t: Status) => STEP.indexOf(s) >= STEP.indexOf(t);

// The demo personalizes this many leads live (keeps the public endpoint within
// its rate limit); the rest still show in the list. Production runs the lot.
const MAX_LIVE = 6;

const COLORS = ["#C9A227", "#5B8DEF", "#3FB984", "#E8557E", "#9B59B6", "#FF7A45", "#19B5A3", "#F4A300"];

const SAMPLE_LEADS: Lead[] = [
  { id: 1, name: "Aisha Rahman", company: "Noor Interiors", interest: "a kitchen renovation quote", city: "Dubai", source: "Instagram ad", color: COLORS[0], reply: "Oh perfect timing — yes please, can you send pricing? 😍" },
  { id: 2, name: "Daniel Okafor", company: "BrightPath Tutoring", interest: "the 1-on-1 SAT prep program", city: "Abu Dhabi", source: "website form", color: COLORS[1], reply: "Great — what slots do you have next week?" },
  { id: 3, name: "Mei Lin Chen", company: "Lotus Wellness", interest: "the monthly membership", city: "Dubai", source: "a referral", color: COLORS[2] },
];

const SAMPLE_CSV = `Name, Company, Interest, City, Source
Omar Khalid, Khalid Motors, a full car detailing package, Sharjah, Instagram
Lina Haddad, Bloom Florist, a weekly office flowers subscription, Dubai, website form
Yusuf Ali, Peak Fitness, the 12-week personal training plan, Abu Dhabi, walk-in
Fatima Noor, Noor Skin Clinic, a hydrafacial package, Dubai, referral`;

const HEADER_HINTS = ["name", "phone", "company", "business", "interest", "want", "need", "city", "location", "source", "note"];

function splitRow(line: string, delim: string): string[] {
  if (delim === "\t") return line.split("\t").map((c) => c.trim());
  const out: string[] = [];
  let cur = "";
  let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQ && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else inQ = !inQ;
    } else if (ch === "," && !inQ) {
      out.push(cur);
      cur = "";
    } else cur += ch;
  }
  out.push(cur);
  return out.map((c) => c.trim());
}

/** Parse pasted spreadsheet rows (tab- or comma-separated) into leads. */
function parseLeads(text: string): Lead[] {
  const lines = text.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  if (!lines.length) return [];
  const delim = lines[0].includes("\t") ? "\t" : ",";
  const rows = lines.map((l) => splitRow(l, delim));
  const first = rows[0].map((c) => c.toLowerCase());
  const hasHeader = first.some((c) => HEADER_HINTS.some((h) => c.includes(h)));

  let idx = { name: 0, company: 1, interest: 2, city: 3, source: 4, phone: -1 };
  let dataRows = rows;
  if (hasHeader) {
    const find = (...keys: string[]) => first.findIndex((c) => keys.some((k) => c.includes(k)));
    idx = {
      name: Math.max(find("name"), 0),
      company: find("company", "business"),
      interest: find("interest", "want", "need", "service", "product", "enquir", "note"),
      city: find("city", "location", "area", "emirate"),
      source: find("source", "channel", "how did"),
      phone: find("phone", "mobile", "number", "whatsapp"),
    };
    dataRows = rows.slice(1);
  }

  const get = (r: string[], k: number) => (k >= 0 && k < r.length ? r[k] : "");
  return dataRows.slice(0, 50).map((r, i) => ({
    id: i + 1,
    name: get(r, idx.name) || `Lead ${i + 1}`,
    company: get(r, idx.company),
    interest: get(r, idx.interest) || "your services",
    city: get(r, idx.city),
    source: get(r, idx.source) || "your list",
    phone: get(r, idx.phone),
    color: COLORS[i % COLORS.length],
  }));
}

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

export default function DemoWhatsApp() {
  const [leads, setLeads] = useState<Lead[]>(SAMPLE_LEADS);
  const [imported, setImported] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [raw, setRaw] = useState("");
  const [status, setStatus] = useState<Record<number, Status>>({});
  const [messages, setMessages] = useState<Record<number, string>>({});
  const [agentReplies, setAgentReplies] = useState<Record<number, string>>({});
  const [activeId, setActiveId] = useState<number>(SAMPLE_LEADS[0].id);
  const [running, setRunning] = useState(false);
  const [done, setDone] = useState(false);
  const [error, setError] = useState("");
  const abort = useRef<AbortController | null>(null);
  const fileRef = useRef<HTMLInputElement | null>(null);

  const active = leads.find((l) => l.id === activeId) ?? leads[0];
  const st = (id: number): Status => status[id] ?? "idle";

  function loadLeads(next: Lead[], isImport: boolean) {
    abort.current?.abort();
    setLeads(next);
    setImported(isImport);
    setStatus({});
    setMessages({});
    setAgentReplies({});
    setActiveId(next[0]?.id ?? 1);
    setRunning(false);
    setDone(false);
    setError("");
  }

  function applyImport(text: string) {
    const parsed = parseLeads(text);
    if (!parsed.length) {
      setError("Couldn't read any leads — check the format (Name, Company, Interest, City).");
      return;
    }
    loadLeads(parsed, true);
    setImportOpen(false);
    setRaw("");
  }

  function onFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => applyImport(String(reader.result ?? ""));
    reader.readAsText(file);
    e.target.value = "";
  }

  function setInterest(id: number, value: string) {
    setLeads((prev) => prev.map((l) => (l.id === id ? { ...l, interest: value } : l)));
  }

  async function sendLead(lead: Lead) {
    setActiveId(lead.id);
    setStatus((s) => ({ ...s, [lead.id]: "writing" }));
    setMessages((m2) => ({ ...m2, [lead.id]: "" }));
    const opener = await streamDemo(
      "/api/demo/whatsapp",
      { name: lead.name, company: lead.company, interest: lead.interest, city: lead.city, source: lead.source },
      (full) => setMessages((m2) => ({ ...m2, [lead.id]: full })),
      abort.current?.signal,
    );
    setStatus((s) => ({ ...s, [lead.id]: "sent" }));
    await sleep(550);
    setStatus((s) => ({ ...s, [lead.id]: "delivered" }));
    await sleep(750);
    setStatus((s) => ({ ...s, [lead.id]: "read" }));
    if (lead.reply) {
      await sleep(1000);
      setStatus((s) => ({ ...s, [lead.id]: "replied" }));
      // Two-way: the AI reads the lead's reply and responds live, qualifying
      // and moving toward a booking — not just an outbound blast.
      await sleep(900);
      setStatus((s) => ({ ...s, [lead.id]: "responding" }));
      setAgentReplies((a) => ({ ...a, [lead.id]: "" }));
      await streamDemo(
        "/api/demo/chat",
        {
          demo: "wa_agent",
          messages: [
            { role: "assistant", content: opener },
            { role: "user", content: lead.reply },
          ],
        },
        (full) => setAgentReplies((a) => ({ ...a, [lead.id]: full })),
        abort.current?.signal,
      );
      setStatus((s) => ({ ...s, [lead.id]: "booked" }));
    }
  }

  async function run() {
    if (running) return;
    track("demo_run", { demo: "whatsapp", leads: imported ? "imported" : "sample", count: Math.min(leads.length, MAX_LIVE) });
    setError("");
    setDone(false);
    setRunning(true);
    setStatus({});
    setMessages({});
    setAgentReplies({});
    abort.current = new AbortController();
    try {
      for (const lead of leads.slice(0, MAX_LIVE)) {
        await sendLead(lead);
        await sleep(450);
      }
      setDone(true);
    } catch (err) {
      if (!(err instanceof DOMException && err.name === "AbortError")) {
        setError(err instanceof Error ? err.message : "Something went wrong.");
      }
    } finally {
      setRunning(false);
    }
  }

  function reset() {
    abort.current?.abort();
    setRunning(false);
    setDone(false);
    setError("");
    setStatus({});
    setMessages({});
    setAgentReplies({});
    setActiveId(leads[0]?.id ?? 1);
  }

  const liveCount = Math.min(leads.length, MAX_LIVE);
  const vals = Object.values(status);
  const stats = {
    generated: vals.filter((s) => reached(s, "sent")).length,
    read: vals.filter((s) => reached(s, "read")).length,
    booked: vals.filter((s) => s === "booked").length,
  };

  return (
    <div className="flex flex-col gap-5">
      {/* source bar — sample vs imported, with the importer toggle */}
      <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-cream/10 bg-ink-deep/40 p-3">
        <FileSpreadsheet size={18} className="text-gold" />
        <p className="text-sm text-cream-dim">
          {imported ? (
            <><b className="text-cream">{leads.length}</b> leads imported from your sheet</>
          ) : (
            <><b className="text-cream">3</b> sample leads loaded</>
          )}
        </p>
        <div className="ml-auto flex items-center gap-2">
          {imported && (
            <button
              type="button"
              onClick={() => loadLeads(SAMPLE_LEADS, false)}
              className="rounded-full px-3 py-1.5 text-xs font-medium text-cream-dim transition-colors hover:text-gold"
            >
              Use sample
            </button>
          )}
          <button
            type="button"
            onClick={() => setImportOpen((v) => !v)}
            className="inline-flex items-center gap-1.5 rounded-full border border-gold/30 bg-gold/10 px-3 py-1.5 text-xs font-semibold text-gold transition-colors hover:bg-gold/20"
          >
            <Sheet size={13} /> Import from Sheets / Excel
          </button>
        </div>
      </div>

      <AnimatePresence initial={false}>
        {importOpen && (
          <m.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden"
          >
            <div className="flex flex-col gap-3 rounded-2xl border border-cream/10 bg-cream/[0.03] p-4">
              <p className="text-sm text-cream-dim">
                Open your Google Sheet or Excel file, select your lead rows, and paste them here — or upload a CSV.
                Columns are matched automatically (<span className="text-cream">Name, Company, Interest, City, Source</span>).
              </p>
              <textarea
                value={raw}
                onChange={(e) => setRaw(e.target.value)}
                rows={5}
                placeholder={"Paste rows from Google Sheets / Excel here…\nName, Company, Interest, City, Source"}
                aria-label="Paste your leads"
                className="w-full resize-none rounded-xl border border-cream/10 bg-ink-deep/50 px-4 py-3 font-mono text-[12.5px] text-cream placeholder:text-muted-dark focus:border-gold/50 focus:outline-none focus:ring-1 focus:ring-gold/40"
              />
              <div className="flex flex-wrap items-center gap-2">
                <button
                  type="button"
                  onClick={() => applyImport(raw)}
                  disabled={raw.trim().length < 3}
                  className="inline-flex items-center gap-2 rounded-full bg-gold px-4 py-2 text-sm font-semibold text-ink-deep transition hover:bg-gold-soft disabled:cursor-not-allowed disabled:opacity-50"
                >
                  Import these leads
                </button>
                <button
                  type="button"
                  onClick={() => fileRef.current?.click()}
                  className="inline-flex items-center gap-1.5 rounded-full border border-cream/15 bg-cream/5 px-4 py-2 text-sm font-medium text-cream transition hover:border-gold/40"
                >
                  <Upload size={14} /> Upload CSV
                </button>
                <button
                  type="button"
                  onClick={() => setRaw(SAMPLE_CSV)}
                  className="ml-auto text-xs text-gold/80 transition-colors hover:text-gold"
                >
                  Paste example data
                </button>
                <input ref={fileRef} type="file" accept=".csv,.tsv,.txt" onChange={onFile} className="hidden" />
              </div>
              <p className="font-mono text-[10px] uppercase tracking-wider text-muted-dark">
                Your data stays in your browser · nothing is uploaded until you run the campaign
              </p>
            </div>
          </m.div>
        )}
      </AnimatePresence>

      {/* controls + live stats */}
      <div className="flex flex-wrap items-center gap-3">
        {!done ? (
          <button
            type="button"
            onClick={run}
            disabled={running}
            className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-2.5 text-sm font-semibold text-ink-deep transition duration-300 hover:bg-gold-soft disabled:cursor-not-allowed disabled:opacity-60"
          >
            {running ? (
              <>
                <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-ink-deep/40 border-t-ink-deep" />
                Sending…
              </>
            ) : (
              <>
                <Play size={15} /> Run the campaign
              </>
            )}
          </button>
        ) : (
          <button
            type="button"
            onClick={reset}
            className="inline-flex items-center gap-2 rounded-full border border-cream/15 bg-cream/5 px-5 py-2.5 text-sm font-semibold text-cream transition hover:border-gold/40"
          >
            <RotateCcw size={15} /> Reset
          </button>
        )}
        <div className="ml-auto flex items-center gap-4 font-mono text-[11px] uppercase tracking-[0.14em] text-muted-dark">
          <span><b className="text-cream">{stats.generated}</b> sent</span>
          <span><b className="text-[#53bdeb]">{stats.read}</b> read</span>
          <span><b className="text-[#3FB984]">{stats.booked}</b> booked</span>
        </div>
      </div>

      <div className="grid gap-5 md:grid-cols-[1fr_300px]">
        {/* lead list */}
        <div className="flex flex-col gap-2.5">
          <p className="font-mono text-[10px] uppercase tracking-wider text-muted-dark">
            Contact leads · edit any interest, then run
          </p>
          <div className="flex max-h-[430px] flex-col gap-2.5 overflow-y-auto pr-1">
            {leads.map((lead, i) => {
              const s = st(lead.id);
              const initials = lead.name.split(" ").map((p) => p[0]).join("").slice(0, 2);
              const skipped = i >= MAX_LIVE;
              return (
                <button
                  type="button"
                  key={lead.id}
                  onClick={() => setActiveId(lead.id)}
                  className={`flex items-center gap-3 rounded-2xl border p-3 text-left transition ${
                    lead.id === activeId ? "border-gold/40 bg-cream/[0.06]" : "border-cream/10 bg-ink-deep/40 hover:border-cream/20"
                  } ${skipped ? "opacity-50" : ""}`}
                >
                  <span
                    className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-xs font-semibold text-ink-deep"
                    style={{ background: lead.color }}
                  >
                    {initials}
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="flex items-center justify-between gap-2">
                      <span className="truncate text-sm font-medium text-cream">{lead.name}</span>
                      {skipped ? (
                        <span className="shrink-0 rounded-full bg-cream/5 px-2 py-0.5 text-[10px] font-medium text-muted-dark">Queued (prod)</span>
                      ) : (
                        <StatusBadge status={s} />
                      )}
                    </span>
                    <span className="mt-1 block truncate text-[11px] text-muted-dark">
                      {[lead.company, lead.city].filter(Boolean).join(" · ") || "—"}
                    </span>
                    <span className="mt-1.5 flex items-center gap-1.5">
                      <span className="text-[11px] text-muted-dark">↳</span>
                      <input
                        value={lead.interest}
                        onChange={(e) => setInterest(lead.id, e.target.value)}
                        onClick={(e) => e.stopPropagation()}
                        disabled={running}
                        aria-label={`Interest for ${lead.name}`}
                        className="w-full bg-transparent text-[12.5px] text-cream-dim outline-none placeholder:text-muted-dark focus:text-cream disabled:opacity-70"
                      />
                    </span>
                  </span>
                </button>
              );
            })}
          </div>
        </div>

        {/* WhatsApp phone */}
        <PhoneMock lead={active} status={st(active.id)} message={messages[active.id]} agentReply={agentReplies[active.id]} />
      </div>

      {error && <p className="text-xs text-gold">{error}</p>}

      <p className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-dark">
        {leads.length > MAX_LIVE
          ? `Openers + replies are written live by the AI for the first ${liveCount} · production runs all ${leads.length} through the WhatsApp Business API`
          : "Openers AND replies are written live by the AI — it personalizes, then handles the conversation and books. Production runs through the WhatsApp Business API."}
      </p>
    </div>
  );
}

function StatusBadge({ status }: { status: Status }) {
  const map: Record<Status, { t: string; c: string }> = {
    idle: { t: "Queued", c: "bg-cream/5 text-muted-dark" },
    writing: { t: "AI writing…", c: "bg-gold/15 text-gold" },
    sent: { t: "Sent", c: "bg-cream/10 text-cream-dim" },
    delivered: { t: "Delivered", c: "bg-cream/10 text-cream-dim" },
    read: { t: "Read", c: "bg-[#53bdeb]/15 text-[#53bdeb]" },
    replied: { t: "Replied", c: "bg-[#3FB984]/15 text-[#3FB984]" },
    responding: { t: "AI replying…", c: "bg-gold/15 text-gold" },
    booked: { t: "Booked ✓", c: "bg-[#3FB984]/20 text-[#3FB984]" },
  };
  const b = map[status];
  return <span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-medium ${b.c}`}>{b.t}</span>;
}

function PhoneMock({
  lead,
  status,
  message,
  agentReply,
}: {
  lead: Lead;
  status: Status;
  message?: string;
  agentReply?: string;
}) {
  const initials = lead.name.split(" ").map((p) => p[0]).join("").slice(0, 2);
  return (
    <div className="mx-auto w-full max-w-[300px] overflow-hidden rounded-[26px] border-[6px] border-black/70 bg-[#0b141a] shadow-2xl">
      {/* header */}
      <div className="flex items-center gap-2.5 bg-[#1f2c33] px-3 py-2.5">
        <span
          className="flex h-8 w-8 items-center justify-center rounded-full text-[11px] font-semibold text-ink-deep"
          style={{ background: lead.color }}
        >
          {initials}
        </span>
        <span className="min-w-0 flex-1">
          <span className="block truncate text-[13px] font-medium text-white">{lead.name}</span>
          <span className="block h-3.5 text-[10.5px] text-[#8aa0a8]">
            {status === "writing" || status === "responding" ? "typing…" : "online"}
          </span>
        </span>
        <HeaderIcons />
      </div>

      {/* chat */}
      <div
        className="flex min-h-[260px] flex-col gap-2 px-3 py-3.5"
        style={{
          backgroundColor: "#0b141a",
          backgroundImage: "radial-gradient(rgba(255,255,255,0.025) 1px, transparent 1px)",
          backgroundSize: "16px 16px",
        }}
      >
        <span className="mx-auto rounded-md bg-[#1d282f] px-2.5 py-0.5 text-[9px] tracking-wide text-[#8aa0a8]">
          TODAY
        </span>

        {status === "writing" && !message && <Typing />}

        {message && (
          <m.div
            initial={{ opacity: 0, scale: 0.97 }}
            animate={{ opacity: 1, scale: 1 }}
            className="ml-auto max-w-[82%] rounded-lg rounded-tr-sm bg-[#144d3c] px-2.5 py-1.5 text-[12.5px] leading-snug text-[#e9fbe8]"
          >
            {message}
            <span className="mt-0.5 flex items-center justify-end gap-1 text-[9px] text-[#e9fbe8]/55">
              now <Ticks status={status} />
            </span>
          </m.div>
        )}

        <AnimatePresence>
          {reached(status, "replied") && lead.reply && (
            <m.div
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              className="mr-auto max-w-[82%] rounded-lg rounded-tl-sm bg-[#1f2c33] px-2.5 py-1.5 text-[12.5px] leading-snug text-white"
            >
              {lead.reply}
              <span className="mt-0.5 block text-right text-[9px] text-white/45">now</span>
            </m.div>
          )}
        </AnimatePresence>

        {status === "responding" && !agentReply && <Typing />}

        {agentReply && (
          <m.div
            initial={{ opacity: 0, scale: 0.97 }}
            animate={{ opacity: 1, scale: 1 }}
            className="ml-auto max-w-[82%] rounded-lg rounded-tr-sm bg-[#144d3c] px-2.5 py-1.5 text-[12.5px] leading-snug text-[#e9fbe8]"
          >
            {agentReply}
            <span className="mt-0.5 flex items-center justify-end gap-1 text-[9px] text-[#e9fbe8]/55">
              now <CheckCheck size={12} className="text-[#53bdeb]" />
            </span>
          </m.div>
        )}

        {status === "idle" && !message && (
          <span className="m-auto px-4 text-center text-[11.5px] leading-relaxed text-[#5f7079]">
            Queued — the AI will write a personalized opener and send it here.
          </span>
        )}
      </div>

      {/* input bar (decorative) */}
      <div className="flex items-center gap-2 bg-[#1f2c33] px-3 py-2">
        <span className="flex-1 rounded-full bg-[#2a3942] px-3 py-1.5 text-[11px] text-[#6b7d85]">
          Type a message
        </span>
        <span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#00a884] text-[#06231b]">
          <Play size={12} className="translate-x-px" />
        </span>
      </div>
    </div>
  );
}

function HeaderIcons() {
  return (
    <span className="flex items-center gap-2 text-[#8aa0a8]">
      <Phone size={13} />
      <MoreVertical size={13} />
    </span>
  );
}

function Ticks({ status }: { status: Status }) {
  if (status === "sent") return <Check size={12} className="text-[#e9fbe8]/55" />;
  if (reached(status, "read")) return <CheckCheck size={12} className="text-[#53bdeb]" />;
  if (reached(status, "delivered")) return <CheckCheck size={12} className="text-[#e9fbe8]/55" />;
  return <Check size={12} className="text-[#e9fbe8]/55" />;
}

function Typing() {
  return (
    <div className="ml-auto flex items-center gap-1 rounded-lg rounded-tr-sm bg-[#144d3c] px-3 py-2.5">
      {[0, 1, 2].map((i) => (
        <m.span
          key={i}
          className="h-1.5 w-1.5 rounded-full bg-[#7da99b]"
          animate={{ opacity: [0.3, 1, 0.3] }}
          transition={{ duration: 1.1, repeat: Infinity, delay: i * 0.18 }}
        />
      ))}
    </div>
  );
}
