import sharp from "sharp";
import { readdirSync, mkdirSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { join, dirname, extname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const RAW = join(root, "work-raw");
const OUT = join(root, "public/work");

// Drop raw originals here (gitignored). Run: npm run images
const CATS = [
  { key: "web", label: "Web Design", featured: 4 },
  { key: "graphic", label: "Graphic Design", featured: 4 },
];
const EXTS = new Set([".jpg", ".jpeg", ".png", ".webp"]);

// Optional per-image metadata, keyed by raw filename stem (without extension).
// Items with an href render a "Live site" link in the portfolio.
const META = {
  // Titles describe the WORK, not the client. Client names and outbound links
  // to client sites are deliberately absent — the site presents delivered work
  // and measured results instead of named attribution.
  "01-we-aspire": { title: "E-learning platform — Education & training, Dubai" },
  "02-gilani-mobility": { title: "E-commerce store — Healthcare mobility, Dubai" },
  "03-aya-home-spa": { title: "Brand site — Wellness & beauty, Dubai" },
  // 04-fellowship-dubai.png sits outside _raw/web; add a title here if it returns.
};

const items = [];

for (const cat of CATS) {
  const rawDir = join(RAW, cat.key);
  const outDir = join(OUT, cat.key);
  if (!existsSync(rawDir)) continue;
  // clean previous webp outputs (keep .gitkeep)
  if (existsSync(outDir)) {
    for (const f of readdirSync(outDir)) {
      if (f.endsWith(".webp")) rmSync(join(outDir, f));
    }
  }
  mkdirSync(outDir, { recursive: true });

  const files = readdirSync(rawDir)
    .filter((f) => EXTS.has(extname(f).toLowerCase()))
    .sort();

  let n = 0;
  for (const f of files) {
    n += 1;
    const base = `${cat.key}-${String(n).padStart(2, "0")}`;
    const src = join(rawDir, f);
    const meta = await sharp(src).metadata();
    const srcW = meta.width || 1600;
    const srcH = meta.height || 1000;
    const fullW = Math.min(srcW, 1600);
    const fullH = Math.round(srcH * (fullW / srcW));

    await sharp(src)
      .rotate()
      .resize({ width: fullW, withoutEnlargement: true })
      .webp({ quality: 80 })
      .toFile(join(outDir, `${base}.webp`));

    await sharp(src)
      .rotate()
      .resize({ width: 800, withoutEnlargement: true })
      .webp({ quality: 72 })
      .toFile(join(outDir, `${base}-thumb.webp`));

    const stem = f.slice(0, f.length - extname(f).length);
    const itemMeta = META[stem] || {};
    items.push({
      category: cat.key,
      label: cat.label,
      title: itemMeta.title || `${cat.label} ${n}`,
      ...(itemMeta.href ? { href: itemMeta.href } : {}),
      src: `/work/${cat.key}/${base}.webp`,
      thumb: `/work/${cat.key}/${base}-thumb.webp`,
      w: fullW,
      h: fullH,
      featured: n <= cat.featured,
    });
  }
  console.log(`  ${cat.key}: ${files.length} images optimised`);
}

const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export interface WorkItem {
  category: "web" | "graphic";
  label: string;
  title: string;
  href?: string;
  src: string;
  thumb: string;
  w: number;
  h: number;
  featured: boolean;
}

export const WORK_ITEMS: WorkItem[] = ${JSON.stringify(items, null, 2)};

export const WEB_DESIGNS = WORK_ITEMS.filter((i) => i.category === "web");
export const GRAPHIC_DESIGNS = WORK_ITEMS.filter((i) => i.category === "graphic");
export const FEATURED_WORK = WORK_ITEMS.filter((i) => i.featured);
`;
writeFileSync(join(root, "src/data/workItems.ts"), ts);
console.log(`\nWork manifest written: ${items.length} items -> src/data/workItems.ts`);
