import { CASE_STUDIES, SERVICES } from "./content";
import { WEB_DESIGNS, type WorkItem } from "./workItems";

/* ---------------------------------------------------------------------------
 * Homepage data.
 *
 * Everything here is drawn from work that actually exists in this repo or in
 * data/content.ts. No invented tools, metrics, reviews or credentials.
 * ------------------------------------------------------------------------- */

/**
 * The stack actually in use, with each brand's own mark where one is
 * licensed for reuse. Generated by `npm run logos`; see
 * scripts/build-tool-logos.mjs for where the marks come from and why three
 * of them are lettermarks instead.
 *
 * The section is labelled "Tools I work with", which is what makes showing
 * the marks nominative use rather than an implied endorsement. Reword that
 * label and the logos need rethinking.
 */
export { TOOL_LOGOS as TOOLS } from "./toolLogos";
export type { ToolLogo as Tool } from "./toolLogos";

/** Core offerings, trimmed to the compact card. */
export const CORE_SERVICES = SERVICES.slice(0, 5).map((s) => s.title);

/**
 * Documented outcomes, pulled straight from the case studies that carry real
 * measured numbers. Case studies without metrics are represented by scope
 * instead, so nothing is inflated into a statistic it never was.
 */
export interface FeaturedResult {
  slug: string;
  client: string;
  category: string;
  location: string;
  stats: { value: string; label: string }[];
}

export const FEATURED_RESULTS: FeaturedResult[] = CASE_STUDIES.filter(
  (study) => study.stats && study.stats.length > 0,
).map((study) => ({
  slug: study.slug,
  client: study.client,
  category: study.category,
  location: study.location,
  stats: study.stats!.slice(0, 3),
}));

/**
 * Which builds lead the home page, newest first.
 *
 * Named rather than taken off the top of the archive. The rule used to be
 * "the first three with a live link", which really meant "whichever three
 * happen to sort first in work-raw/" — so a new project could not reach the
 * home page without renumbering every source file and changing nineteen
 * image URLs to do it. Naming them makes this the editorial choice it always
 * was, and leaves the archive's own ordering alone.
 *
 * Matched on the client name rather than the image path, so renumbering the
 * archive later cannot quietly empty this list.
 *
 * Three, and three is the ceiling: the home page has to fit one screen, and a
 * fourth row costs about 41px, which took 1440x760 to 801. The reel beside
 * the list scrolls and would take more, but the captions next to it will not.
 * Adding one here means dropping one, or giving up that viewport.
 */
const HOME_PROJECT_CLIENTS = [
  "Construction Desert Schools",
  "We Aspire",
  "Gilani Mobility",
];

/**
 * Previews shown in the Projects card.
 *
 * Only builds carrying the live site's URL qualify, so every image is a real
 * screenshot of the site it is captioned with — no logo stands in for a
 * screenshot, and no screenshot is captioned with the wrong client. A name
 * that matches nothing is dropped rather than rendered blank.
 *
 * `title` is "Client · descriptor" in workItems.ts; the split keeps the client
 * name on its own line and the descriptor beneath it.
 */
export const FEATURED_PROJECTS = HOME_PROJECT_CLIENTS.map((client) =>
  WEB_DESIGNS.find((item) => item.href && item.title.startsWith(`${client} ·`)),
)
  .filter((item): item is WorkItem => item !== undefined)
  .map((item) => {
    const [client, ...restOfTitle] = item.title.split(" · ");
    return {
      client: client.trim(),
      descriptor: restOfTitle.join(" · ").trim(),
      image: item.thumb,
      /** Full original title, for the image's alt text. */
      title: item.title,
    };
  });

export const HERO = {
  // Plain words on purpose: the people this is for run 2-10 person businesses
  // in a city where English is often a second language, so "systems", "stack"
  // and "wired" are words they skim past. Short also buys fold space, and the
  // home page has to land inside one viewport.
  headline: "Less admin. More business.",
  // The headline is memorable but says nothing about the offer, so this line
  // carries the whole "what and for whom". Literal on purpose: it is also what
  // a search engine or an AI assistant will quote when describing the site.
  subhead: "Websites, CRM, Odoo and AI automation for small businesses in Dubai.",
  ctaLabel: "Get in touch",
  // /contact, not /#contact: the home page no longer carries a contact
  // section, so the anchor it used to target isn't there to scroll to.
  ctaHref: "/contact",
};
