// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export interface WorkItem {
  category: "web" | "graphic";
  label: string;
  src: string;
  thumb: string;
  w: number;
  h: number;
  featured: boolean;
}

export const WORK_ITEMS: WorkItem[] = [
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-01.webp",
    "thumb": "/work/web/web-01-thumb.webp",
    "w": 600,
    "h": 2419,
    "featured": true
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-02.webp",
    "thumb": "/work/web/web-02-thumb.webp",
    "w": 1400,
    "h": 1050,
    "featured": true
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-03.webp",
    "thumb": "/work/web/web-03-thumb.webp",
    "w": 1400,
    "h": 1050,
    "featured": true
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-04.webp",
    "thumb": "/work/web/web-04-thumb.webp",
    "w": 400,
    "h": 1856,
    "featured": true
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-05.webp",
    "thumb": "/work/web/web-05-thumb.webp",
    "w": 500,
    "h": 1622,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-06.webp",
    "thumb": "/work/web/web-06-thumb.webp",
    "w": 1400,
    "h": 1050,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-07.webp",
    "thumb": "/work/web/web-07-thumb.webp",
    "w": 1400,
    "h": 1050,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-08.webp",
    "thumb": "/work/web/web-08-thumb.webp",
    "w": 1600,
    "h": 1067,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-09.webp",
    "thumb": "/work/web/web-09-thumb.webp",
    "w": 500,
    "h": 1516,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-10.webp",
    "thumb": "/work/web/web-10-thumb.webp",
    "w": 500,
    "h": 1558,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-11.webp",
    "thumb": "/work/web/web-11-thumb.webp",
    "w": 600,
    "h": 2044,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-12.webp",
    "thumb": "/work/web/web-12-thumb.webp",
    "w": 1400,
    "h": 800,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-13.webp",
    "thumb": "/work/web/web-13-thumb.webp",
    "w": 300,
    "h": 1843,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-14.webp",
    "thumb": "/work/web/web-14-thumb.webp",
    "w": 1600,
    "h": 1200,
    "featured": false
  },
  {
    "category": "web",
    "label": "Web Design",
    "src": "/work/web/web-15.webp",
    "thumb": "/work/web/web-15-thumb.webp",
    "w": 1400,
    "h": 933,
    "featured": false
  },
  {
    "category": "graphic",
    "label": "Graphic Design",
    "src": "/work/graphic/graphic-01.webp",
    "thumb": "/work/graphic/graphic-01-thumb.webp",
    "w": 1000,
    "h": 660,
    "featured": true
  },
  {
    "category": "graphic",
    "label": "Graphic Design",
    "src": "/work/graphic/graphic-02.webp",
    "thumb": "/work/graphic/graphic-02-thumb.webp",
    "w": 1200,
    "h": 746,
    "featured": true
  },
  {
    "category": "graphic",
    "label": "Graphic Design",
    "src": "/work/graphic/graphic-03.webp",
    "thumb": "/work/graphic/graphic-03-thumb.webp",
    "w": 1400,
    "h": 933,
    "featured": true
  },
  {
    "category": "graphic",
    "label": "Graphic Design",
    "src": "/work/graphic/graphic-04.webp",
    "thumb": "/work/graphic/graphic-04-thumb.webp",
    "w": 1400,
    "h": 924,
    "featured": true
  },
  {
    "category": "graphic",
    "label": "Graphic Design",
    "src": "/work/graphic/graphic-05.webp",
    "thumb": "/work/graphic/graphic-05-thumb.webp",
    "w": 1200,
    "h": 746,
    "featured": false
  },
  {
    "category": "graphic",
    "label": "Graphic Design",
    "src": "/work/graphic/graphic-06.webp",
    "thumb": "/work/graphic/graphic-06-thumb.webp",
    "w": 1400,
    "h": 1050,
    "featured": false
  },
  {
    "category": "graphic",
    "label": "Graphic Design",
    "src": "/work/graphic/graphic-07.webp",
    "thumb": "/work/graphic/graphic-07-thumb.webp",
    "w": 1400,
    "h": 1050,
    "featured": false
  },
  {
    "category": "graphic",
    "label": "Graphic Design",
    "src": "/work/graphic/graphic-08.webp",
    "thumb": "/work/graphic/graphic-08-thumb.webp",
    "w": 1400,
    "h": 924,
    "featured": false
  },
  {
    "category": "graphic",
    "label": "Graphic Design",
    "src": "/work/graphic/graphic-09.webp",
    "thumb": "/work/graphic/graphic-09-thumb.webp",
    "w": 1200,
    "h": 746,
    "featured": false
  }
];

export const WEB_DESIGNS = WORK_ITEMS.filter((i) => i.category === "web");
export const GRAPHIC_DESIGNS = WORK_ITEMS.filter((i) => i.category === "graphic");
export const FEATURED_WORK = WORK_ITEMS.filter((i) => i.featured);
